CREATE TABLE CLIENTS
(
  NAME         VARCHAR(255) PRIMARY KEY NOT NULL,
  PASSWORD     VARCHAR(255)             NOT NULL,
  LOCK_VERSION INT DEFAULT 0            NOT NULL
);
CREATE TABLE CONSUMERS
(
  ID                 BIGINT PRIMARY KEY NOT NULL,
  CLIENT_NAME        VARCHAR(255)       NOT NULL,
  LAST_ACTIVITY      BIGINT             NOT NULL,
  SOLVED_LAST_PUZZLE SMALLINT           NOT NULL,
  NAME               VARCHAR(255)       NOT NULL,
  PROFILE_NAME       VARCHAR(255)       NOT NULL,
  ANSWER             VARCHAR(255)       NOT NULL,
  CREATION_TIME      BIGINT             NOT NULL
);
CREATE TABLE PROFILES
(
  CLIENT_NAME  VARCHAR(255)  NOT NULL,
  NAME         VARCHAR(255)  NOT NULL,
  CONSUMER_TTL BIGINT        NOT NULL,
  PUZZLE_TTL   BIGINT        NOT NULL,
  LOCK_VERSION INT DEFAULT 0 NOT NULL,
  PRIMARY KEY (CLIENT_NAME, NAME)
);
CREATE TABLE ROLES
(
  CLIENT VARCHAR(255) NOT NULL,
  ROLE   VARCHAR(20)  NOT NULL,
  PRIMARY KEY (CLIENT, ROLE)
);
CREATE SEQUENCE CONSUMER_ID_SEQ
  AS BIGINT MINVALUE 1 NO MAXVALUE START WITH 1 INCREMENT BY 1 CYCLE;

ALTER TABLE CONSUMERS
  ADD FOREIGN KEY (CLIENT_NAME)
  REFERENCES CLIENTS (NAME);
ALTER TABLE CONSUMERS
  ADD FOREIGN KEY (CLIENT_NAME, PROFILE_NAME)
  REFERENCES PROFILES (CLIENT_NAME, NAME);
ALTER TABLE PROFILES
  ADD FOREIGN KEY (CLIENT_NAME)
  REFERENCES CLIENTS (NAME);
ALTER TABLE ROLES
  ADD FOREIGN KEY (CLIENT)
  REFERENCES CLIENTS (NAME);

CREATE INDEX I_CNSUMRS_PROFILE ON CONSUMERS (PROFILE_NAME, CLIENT_NAME);

INSERT INTO
  CLIENTS (NAME, PASSWORD, LOCK_VERSION)
  VALUES (
    'admin',
    'JOJO0475556B4BE1E3E1B741796552A9F7C6E875C008A876C9BD637D910E22FF1C244F',
    0);
INSERT INTO
  ROLES (CLIENT, ROLE)
  VALUES ('admin', 'ADMIN');
